cat \
js/draw/Sprite.js \
js/draw/Text.js \
js/draw/Board.js \
js/draw/pieces/Tetromino.js \
js/draw/pieces/RhodeIslandZ.js \
js/draw/pieces/ClevelandZ.js \
js/draw/pieces/Teewee.js \
js/draw/pieces/Smashboy.js \
js/draw/pieces/BlueRicky.js \
js/draw/pieces/OrangeRicky.js \
js/draw/pieces/Hero.js \
js/etc/Input.js \
js/etc/Sound.js \
js/etc/Vector.js \
js/etc/Timer.js \
js/scene/Scene.js \
js/scene/CreditsScene.js \
js/scene/TitleScene.js \
js/scene/GameMenuScene.js \
js/scene/LevelSelectScene.js \
js/scene/BTypeScoringScene.js \
js/scene/BTypeWinScene.js \
js/scene/GameScene.js \
js/scene/LoseScene.js \
js/scene/PauseScene.js \
js/scene/RocketScene.js \
js/scene/SceneManager.js \
js/index.js \
> jstetris.js